module.exports = [
    {
        username: "koko",
        password: "koko",
        sex: "Male",
        work: "dunerjiq",
        email: "TheBestKokoInVarna@abv.bg",
        description: "Dunerche za vseki",
        orientation: "Heterosexual",
        years: 21,
        position: "Top",
        height: 183,
        weight: 110,
        bodytype: "Stocky",
        relationshipStatus: "Single",
        nsfw: "No",
    },
    {
        username: "toshko",
        password: "toshko",
        sex: "Male",
        work: "bodybuilder",
        email: "TheBestToshkoInVarna@abv.bg",
        description: "Fitnesche za vseki",
        orientation: "Heterosexual",
        years: 21,
        position: "Versalite",
        height: 173,
        weight: 85,
        bodytype: "Muscular",
        relationshipStatus: "Single",
        nsfw: "No",
    },
    {
        username: "valio",
        password: "valio",
        sex: "Male",
        work: "Billa",
        email: "TheBestValioInVarna@abv.bg",
        description: "Billa za vseki",
        orientation: "Asexual",
        years: 21,
        position: "Top",
        height: 177,
        weight: 96,
        bodytype: "Average",
        relationshipStatus: "Single",
        nsfw: "Yes",
    },
    {
        username: "dobrin",
        password: "dobrin",
        sex: "Male",
        work: "puteshestvenik",
        email: "TheBestDobaInVarna@abv.bg",
        description: "Vakanciika za vseki",
        orientation: "Heterosexual",
        years: 21,
        position: "Top",
        height: 193,
        weight: 105,
        bodytype: "Stocky",
        relationshipStatus: "Dating",
        nsfw: "No",
    },
    {
        username: "martin",
        password: "martin",
        sex: "Male",
        work: "dostavchik",
        email: "TheBestMartoInVarna@abv.bg",
        description: "Stoka za vseki",
        orientation: "Heterosexual",
        years: 21,
        position: "Top",
        height: 184,
        weight: 83,
        bodytype: "Average",
        relationshipStatus: "Single",
        nsfw: "Yes",
    },
    {
        username: "veselin",
        password: "veselin",
        sex: "Male",
        work: "at home",
        email: "TheBestVeskoInVarna@abv.bg",
        description: "Kushta za vseki",
        orientation: "Gay",
        years: 21,
        position: "Versalite",
        height: 185,
        weight: 82,
        bodytype: "Average",
        relationshipStatus: "Single",
        nsfw: "Yes",
    },
    {
        username: "ioana",
        password: "ioana",
        sex: "Female",
        work: "Billa",
        email: "TheBestIoniInVarna@abv.bg",
        description: "Billa za vseki",
        orientation: "Bisexual",
        years: 21,
        position: "Versalite",
        height: 171,
        weight: 53,
        bodytype: "Toned",
        relationshipStatus: "Single",
        nsfw: "No",
    },
    {
        username: "jenq",
        password: "jenq",
        sex: "Female",
        work: "Sitel",
        email: "TheBestJenqInVarna@abv.bg",
        description: "Sitel za vseki",
        orientation: "Allosexual",
        years: 21,
        position: "Versalite",
        height: 169,
        weight: 55,
        bodytype: "Average",
        relationshipStatus: "Single",
        nsfw: "No",
    },
    {
        username: "vesi",
        password: "vesi",
        sex: "Female",
        work: "at home",
        email: "TheBestVesiInVarna@abv.bg",
        description: "Kushta za vseki",
        orientation: "Heterosexual",
        years: 21,
        position: "Versalite",
        height: 170,
        weight: 55,
        bodytype: "Average",
        relationshipStatus: "Single",
        nsfw: "No",
    },
    {
        username: "aleks",
        password: "aleks",
        sex: "Male",
        work: "programmer",
        email: "TheBestSashkoInVarna@abv.bg",
        description: "Programa za vseki",
        orientation: "Pansexual",
        years: 32,
        position: "Vers Top",
        height: 190,
        weight: 95,
        bodytype: "Muscular",
        relationshipStatus: "Open Relationship",
        nsfw: "Yes",
    },
    {
        username: "tuce",
        password: "tuce",
        sex: "Female",
        work: "student",
        email: "TheBestTuceInVarna@abv.bg",
        description: "Uchkane za vseki",
        orientation: "Monosexual",
        years: 22,
        position: "Bottom",
        height: 165,
        weight: 60,
        bodytype: "Average",
        relationshipStatus: "Married",
        nsfw: "No",
    },
    {
        username: "nikol",
        password: "nikol",
        sex: "Female",
        work: "Manager",
        email: "TheBestNikolInVarna@abv.bg",
        description: "Ikonomika za vseki",
        orientation: "Bisexual",
        years: 23,
        position: "Versalite",
        height: 175,
        weight: 56,
        bodytype: "Average",
        relationshipStatus: "Single",
        nsfw: "No",
    },
    {
        username: "petur",
        password: "petur",
        sex: "Male",
        work: "Photographer",
        email: "TheBestPeshoInVarna@abv.bg",
        description: "Snimchica za vseki",
        orientation: "Gay",
        years: 25,
        position: "Vers Top",
        height: 189,
        weight: 87,
        bodytype: "Toned",
        relationshipStatus: "Commited",
        nsfw: "Yes",
    },
    {
        username: "gosho",
        password: "gosho",
        sex: "Male",
        work: "Cooker",
        email: "TheBestGoshoInVarna@abv.bg",
        description: "Mandja za vseki",
        orientation: "Bisexual",
        years: 27,
        position: "Top",
        height: 183,
        weight: 85,
        bodytype: "Slim",
        relationshipStatus: "Married",
        nsfw: "No",
    },
    {
        username: "dani",
        password: "dani",
        sex: "Transgender",
        work: "Aktivist",
        email: "TheBestDaniInVarna@abv.bg",
        description: "Protest za vseki",
        orientation: "Queer",
        years: 31,
        position: "Bottom",
        height: 196,
        weight: 120,
        bodytype: "Large",
        relationshipStatus: "Exclusive",
        nsfw: "No",
    },
];
